### ISSUE TITLE
Kobold Scale Sorcerer breaks the page

### ISSUE THREAD

**Issue by Marcloure** [mlenser/tabletop-homebrew-issues#13]
Expanding the Kobold Scale Sorcerer on the Monsters page breaks everything to a blank page.

(Just a note, I can't tag issues here).

**Comment by Lamorak11** [comment]
I've noticed that for me a number of monsters do this.
Abyssal Wretch, Androsphinx, Ankheg, Arcanoloth and Archmage all break for me, and that's just the ones beginning with "A".

**Comment by mlenser** [comment]
This is fixed now. Sorry about monsters being a bit unstable. I'm reworking a lot of the underlying system to be more calculated instead of explicit strings. I'll try to load every monster on the page to ensure they work.

**Comment by mlenser** [comment]
I've gone through every monster in the system and have ensured all of them render without errors or warnings.
