### ISSUE TITLE
Redo Wild Shape based on the new Companions

### ISSUE THREAD

**Issue by Marcloure** [mlenser/tabletop-homebrew-issues#17]
> **Traits**
> If the trait listed above does not appear in this list, it is an enhancement.

Maybe it should just say that it's a trait of that animal.

**Comment by mlenser** [comment]
I need to do the same for the Shapeshifter after I do https://github.com/mlenser/tabletop-homebrew-issues/issues/10

**Comment by mlenser** [comment]
Working through this I've decided that this would be better suited as a spell that uses the new companion forms. It works really well.
This would be in place of the Wild Shaper and Shapeshifter.

**Comment by Marcloure** [comment]
What do you mean? Use something like the Polymorph spell in place of the Wild Shaper and Shapeshifter subclasses?

**Comment by mlenser** [comment]
A new spell, ya. I have it all typed up and will finalize it tomorrow.

**Comment by Marcloure** [comment]
I am sure you have considered it, but I'll say it anyway. There are some points to consider:
- Concentration & duration
- Multiattack (I guess it uses the companion progression)
- Magic Weapon

Also, I guess this would mean that a full caster could turn into a half-martial with this spell?

**Comment by mlenser** [comment]
> Concentration & duration

There will be no concentration. The duration is 1 hour/mana.

> Multiattack (I guess it uses the companion progression)
> Magic Weapon

Both of these are covered by the companion scaling

> I guess this would mean that a full caster could turn into a half-martial with this spell?

Yup

**Comment by Marcloure** [comment]
I really liked it, but I have a question.

How is HP handled? I suppose you assume the new form's hp, which probably means you will lose some total hp, but you can self heal. Also, what happens with the damage you took when you revert back?

**Comment by mlenser** [comment]
Clarified:

Your game statistics (including hit points and Hit Dice) are replaced by the statistics of the chosen beast, though you retain your alignment, and Intelligence, Wisdom, and Charisma scores. When you revert to your normal form, you return to the number of hit points you had before you transformed. However, if you revert as a result of dropping to 0 hit points, any excess damage carries over to your normal form.

**Comment by Marcloure** [comment]
Is it intended that when you transform you will often become worse in some skills (for instance, Perception)? You will usually lose a bit of proficiency bonus when you transform and your expertises, so if you are proficient or expert, you will lose 1 to 3 points in that skill.

**Comment by Marcloure** [comment]
Ok, I have a few more questions. 

What about Feats and Class' features? Do you lose all of them? I would say so by the description.

The feature says you can't cast spells, but I believe you also can't use maneuvers that isn't from that form, correct?
