### ISSUE TITLE
Reduce the cost of animate spells now that we have lower challenge elementals

### ISSUE THREAD

**Issue by mlenser** [mlenser/tabletop-homebrew-issues#18]
Spells like `Animate Earth` should cost less mana and summon creatures of lower CR.

**Comment by Marcloure** [comment]
What about Elemental Myrmidon? The lore says that they are elementals trapped inside a suit of armor. Since this is a more specific ritual, do think it should be left to the DM to determine how (and if) a PC can have one?

**Comment by mlenser** [comment]
> do think it should be left to the DM to determine how (and if) a PC can have one?

Ya, I think it's different than these spells. Maybe this spell + some kind of ritual or this spell+ upcasted by 1 on a suit of armor? It seems a bit more complex than a simple spell.
