### ISSUE TITLE
Prismatic Spray augment duration

### ISSUE THREAD

**Issue by Marcloure** [mlenser/tabletop-homebrew-issues#21]
Both the Indigo and Violet augmented colors need a duration.

**Comment by mlenser** [comment]
The RAW version of the spell ist the exact same way:

"6. Indigo. On a failed save, the target is restrained. It must then make a Constitution saving throw at the end of each of its turns. If it successfully saves three times, the spell ends. If it fails its save three times, it permanently turns to stone and is subjected to the petrified condition. The successes and failures don't need to be consecutive; keep track of both until the target collects three of a kind."

**Comment by Marcloure** [comment]
Sorry, I said that because the augment says:

> If the slowed level reaches 4, the creature is turned to stone, no longer makes saving throws each turn, and is subjected to the petrified condition for the **duration**.

**Comment by mlenser** [comment]
edited Prismatic Spray wording to permanently turn to stone like RAW, but be slightly easier to avoid
