### ISSUE TITLE
Divine Intervention success chance

### ISSUE THREAD

**Issue by Marcloure** [mlenser/tabletop-homebrew-issues#22]
The Acolytes's feature says:

> Describe the assistance you seek and if successful, your GM chooses the nature of the intervention [...]. If your deity doesn’t intervene you regain mana equal to your mana limit. 

It doesn't say, however, how to determine if the intervention is successful or not.

**Comment by DalenWBrauner** [comment]
It sounds like this is intended to be based solely on flavor, circumstance and the DM, but I don't think it'd hurt to clarify that.

**Comment by mlenser** [comment]
I clarified the wording so that it is clear that it should happen most of the time, with GM discretion.

Thanks!
