### ISSUE TITLE
Infinite Elementals

### ISSUE THREAD

**Issue by wherfz** [mlenser/tabletop-homebrew-issues#23]
Animate Air/Earth/Fire/Water spells allow you to summon an elemental that can in turn cast Animate Air/Earth/Fire/Water spells this summon can cast the Animate spell. Allowing for a convenient little army as long as you can hold concentration! 

I think this is unintended! It seems way too powerful for an ambush. Otherwise, I really like these animate spells.

**Comment by mlenser** [comment]
Thanks for pointing out this obvious madness. It's fixed now! :)
