### ISSUE TITLE
New Site URLs

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/tabletop-homebrew-issues#24]
Seems that most direct URLs on your new site try to direct to itself, e.g.:
- https://marklenser.com/rpg/https://marklenser.com/5e/rpg
- https://marklenser.com/rpg/https://marklenser.com/rpg/monsters/Will-o%E2%80%99-Wisp

**Comment by mlenser** [comment]
What do you mean "direct URLs"? From where? Did you type in the URL, or click a link, or?

**Comment by Marcloure** [comment]
This issue happens on the Changelog, in the 19.1 patch notes. I think it's a problem only on that page.

**Comment by DalenWBrauner** [comment]
(Sorry for not responding to this, I thought I had email notifications set up properly.)
