### ISSUE TITLE
Colapse Themes's fields

### ISSUE THREAD

**Issue by Marcloure** [mlenser/tabletop-homebrew-issues#27]
I don't know how doable it is, but I think it would be neat if Feats, Concoctions, Maneuvers, and Spells were hideable. With that I mean you could colapse the Concoctions field and reduce the size of the page (not each individual concoction, but the entire Concoctions section).

Also, if possible, save that as a cookie so that it remains collapsed as the user desires.

**Comment by mlenser** [comment]
The problems with collapsible sections:

- They hide information from user searches on a page
- If you don't want to see concoctions/maneuvers it would be cumbersome to hide the maneuvers section on every theme
- It would require a lot of local storage variables for each user to store this information.

What is the goal you're trying to achieve? Not see concoctions/maneuvers?

**Comment by Marcloure** [comment]
> What is the goal you're trying to achieve? Not see concoctions/maneuvers?

Yes, that is the goal. I have a player who uses mobile to check the site, and some themes (specially Beast) have a lot of different stuff before you can see your maneuvers or spells. Every time you go check a thing, you have to scroll all the way down. Even on desktop you have to scroll quite a lot to reach 2 mana spells on Beast.

**Comment by mlenser** [comment]
Added a table of contents to each theme with links to scroll to sections (feats, concoctions, maneuvers, spells) and back to the top
