### ISSUE TITLE
Animate Elemental should be at 2 mana

### ISSUE THREAD

**Issue by Marcloure** [mlenser/tabletop-homebrew-issues#28]
By expending 1 mana, you can create a creature that has 1 mana and a bunch of hp and some damage.

It's way better to animate a small water elemental with ebb and flow than use the spell yourself, since you also gain an elemental and other spell options that you might not have.

**Comment by mlenser** [comment]
This problem, if it is a problem, is not unique to Animate spells. It would also exist for Call Beast and other spells that summon.
All monsters will have maneuvers or spells given time so the issue, if it is an issue, needs to be solved in a way that applies everywhere.

**Comment by mlenser** [comment]
- Call Beast must now expend mana for the beast to have stamina dice
- Animate Acid must now expend mana for the beast to have stamina dice
- Animate Air must now expend mana for the beast to have stamina dice
- Animate Earth must now expend mana for the beast to have stamina dice
- Animate Flames must now expend mana for the beast to have stamina dice
- Animate Ice must now expend mana for the beast to have stamina dice
- Animate Sand must now expend mana for the beast to have stamina dice
- Animate Storm must now expend mana for the beast to have stamina dice
- Animate Water must now expend mana for the beast to have stamina dice
