### ISSUE TITLE
Drown spell issues

### ISSUE THREAD

**Issue by Marcloure** [mlenser/tabletop-homebrew-issues#29]
First, it has no damage type. I think it should deal necrotic damage? I'm not sure.

Second, creatures that don't need to breath or can breath underwater should be immune to the spell.

**Comment by mlenser** [comment]
Drown now causes a target to lose hp instead of take damage—the spell is unique enough to warrant such a divergence from the damage system. Additionally it now explicitly has no effect on a create that does not breathe
