### ISSUE TITLE
Tree Form compared to Polymorph

### ISSUE THREAD

**Issue by Marcloure** [mlenser/tabletop-homebrew-issues#31]
Tree Form (mana 3) transforms you into a CR 2 Awakened Tree.

Polymorph (at mana 3) transforms you into a CR 3 beast, and allows you to keep your proficiency, mental stats, and can be used on allies.

Now that we have Wild Shape as a spell, maybe Polymorph should be toned down to closer to the PHB version (you lose your proficiencies and mental stats). Or Tree Form should get a buff.

**Comment by mlenser** [comment]
Tree Form can be handled by https://github.com/mlenser/tabletop-homebrew-issues/issues/33

**Comment by mlenser** [comment]
I think Polymorph should potentially be removed except Baleful Polymorph.

Wild Shape and similar spells could have an augment to cast on another creature (making it weaker for them than on you, which is good).

**Comment by mlenser** [comment]
Tree Form changed from 3 mana to 1 mana and altered to turn you into a companion form similar to Wild Shape

**Comment by mlenser** [comment]
So Pathfinder 2e did exactly what I was thinking: https://2e.aonprd.com/Traits.aspx?ID=127

**Comment by mlenser** [comment]
- Wild Shape can be augmented to be cast on a willing creature
- Tree Shape can be augmented to be cast on a willing creature

**Comment by mlenser** [comment]
Wild Shape changed from 1 mana to 2 mana

**Comment by mlenser** [comment]
Wild Shape no longer allows you to use the companion’s stamina dice. Otherwise it’s an exponential benefit
