### ISSUE TITLE
Minor Companion feats issues

### ISSUE THREAD

**Issue by Marcloure** [mlenser/tabletop-homebrew-issues#41]
I have some issues with the new version of these Feats. Mostly minor stuff.

**1)** Steel Construct says "You always call the same construct". That doesn't make sense for this specific feat (create Homunculus has that line removed).

**2)** The feat should extend the spell's duration until you finish a short rest, where you can cast the spell again as part of the rest. Otherwise, the beast will leave you every few hours.

**3)** As this is a Feat, should it allow you to call the companion with full mana/stamina?

**Comment by mlenser** [comment]
> 1) Steel Construct says "You always call the same construct". That doesn't make sense for this specific feat (create Homunculus has that line removed).

Homunculus only has 1 possible form. Steel Construct has tons of forms to choose from, but is limited to 1 for the feat's purpose. I updated the wording to be:
"You always construct the same form."

> 2) The feat should extend the spell's duration until you finish a short rest, where you can cast the spell again as part of the rest. Otherwise, the beast will leave you every few hours.

Done. Feat companions last until you finish a short or long rest. Example:
"You can spend 10 minutes to cast *create homunculus*, changing the duration to last until you finish a short or long rest and removing the need to concentrate on the spell."

> 3) As this is a Feat, should it allow you to call the companion with full mana/stamina?

Nope, that'd be insanely strong. The earlier version required that you lose an amount of mana equal to your mana limit. This is similar.
Long duration (free mana) and no concentration are worth a feat.

**Comment by Marcloure** [comment]
There is also the Naturalists's Animal Companion Primal Call, but maybe that should be kept weaker than the feat? You call a beast and it fights by your side for a few hours before wandering off.
