### ISSUE TITLE
Rename the Construct Steel Construct spell

### ISSUE THREAD

**Issue by Marcloure** [mlenser/tabletop-homebrew-issues#42]
Rename Construct Steel Construct to Create Steel Construct

**Comment by mlenser** [comment]
Construct has a nicer ring to it for a mechanical creature. :)

**Comment by Marcloure** [comment]
Well, I agree with that. I was saying that because of the repetition of the word "construct", but I think there is no problem there

**Comment by Marcloure** [comment]
Hey, out of topic, do you receive notifications for closed issues? I posted a comment on #21 to why I created that issue

**Comment by mlenser** [comment]
Yes, I do. Sorry, I forgot about that one.

**Comment by mlenser** [comment]
Repetition is kind of fun.

**Comment by mlenser** [comment]
Steel Construct feat renamed Steel Defender
